- name: Ensure apt cache is updated
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install required helper packages
  ansible.builtin.apt:
    name:
      - software-properties-common
      - dirmngr
    state: present
    install_recommends: no
  become: true

- name: Add CRAN signing key
  ansible.builtin.get_url:
    url: https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc
    dest: /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
    mode: '0644'
  become: true

- name: Add CRAN repository
  ansible.builtin.apt_repository:
    repo: "deb https://cloud.r-project.org/bin/linux/ubuntu {{ ansible_lsb.codename }}-cran40/"
    state: present
    filename: cran-r
  become: true

- name: Install R base package
  ansible.builtin.apt:
    name: r-base
    state: present
    install_recommends: no
  become: true

- name: Install system dependencies for tidyverse
  ansible.builtin.apt:
    name:
      - libcurl4-openssl-dev
      - libssl-dev
      - libxml2-dev
    state: present
  become: true

- name: Install tidyverse R package
  ansible.builtin.shell: |
    Rscript -e "if (!requireNamespace('tidyverse', quietly = TRUE)) install.packages('tidyverse', repos='https://cloud.r-project.org')"
  args:
    executable: /bin/bash
  become: true
