---
- name: install apt packages
  hosts: localhost
  become: true

  roles:
    - apt

- name: nerdfont 
  hosts: localhost
  become: true

  roles:
    - nerdfont

- name: docker 
  hosts: localhost
  become: true

  roles:
    - docker

- name: obsidian
  hosts: localhost
  become: true

  roles:
    - obsidian

- name: kitty 
  hosts: localhost
  become: false

  roles:
    - kitty
      
- name: lazygit
  hosts: localhost
  become: false

  roles:
    - lazygit

- name: neovim
  hosts: localhost
  become: true

  roles:
    - neovim

- name: nodejs
  hosts: localhost
  become: true

  roles:
    - nodejs

- name: R
  hosts: localhost
  become: true

  roles:
    - R

- name:
  hosts: localhost
  become: false

  roles:
    - starship
