---
- name: Provision Tuxedo OS
  hosts: localhost
  become: true

  pre_tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - role: hurricanehrndz.nerdfonts
      vars:
        nerdfonts_fonts:
          - fontname: 'JetBrainsMono'
        nerdfonts_mono: yes

- name: Install kitty using chriscroome.kitty role
  hosts: localhost
  become: no
  roles:
    - chriscroome.kitty
