- name: Ensure required directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ ansible_user_dir }}/.local/bin"
    - "{{ ansible_user_dir }}/.local/share/applications"
    - "{{ ansible_user_dir }}/.config"

- name: (Re)install or update kitty terminal
  ansible.builtin.shell: |
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  args:
    chdir: "{{ ansible_user_dir }}"
    creates: "{{ ansible_user_dir }}/.local/kitty.app"  # Optional: skip if already installed
  environment:
    HOME: "{{ ansible_user_dir }}"
  register: kitty_install_result
  changed_when: true  # Forces re-run if you always want the latest

- name: Ensure symlinks for kitty and kitten binaries
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/.local/kitty.app/bin/{{ item }}"
    dest: "{{ ansible_user_dir }}/.local/bin/{{ item }}"
    state: link
    force: true
  loop:
    - kitty
    - kitten

- name: Copy kitty desktop entries
  ansible.builtin.copy:
    src: "{{ ansible_user_dir }}/.local/kitty.app/share/applications/{{ item }}"
    dest: "{{ ansible_user_dir }}/.local/share/applications/{{ item }}"
    remote_src: yes
    force: true
  loop:
    - kitty.desktop
    - kitty-open.desktop

- name: Update icon path in desktop files
  ansible.builtin.replace:
    path: "{{ ansible_user_dir }}/.local/share/applications/{{ item }}"
    regexp: 'Icon=kitty'
    replace: "Icon={{ ansible_user_dir }}/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png"
  loop:
    - kitty.desktop
    - kitty-open.desktop

- name: Update Exec path in desktop files
  ansible.builtin.replace:
    path: "{{ ansible_user_dir }}/.local/share/applications/{{ item }}"
    regexp: 'Exec=kitty'
    replace: "Exec={{ ansible_user_dir }}/.local/kitty.app/bin/kitty"
  loop:
    - kitty.desktop
    - kitty-open.desktop

- name: Make xdg-terminal-exec prefer kitty
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/xdg-terminals.list"
    content: "kitty.desktop\n"
    mode: '0644'

