- name: Install Starship using andrewrothstein.starship
  include_role:
    name: andrewrothstein.starship

- name: Ensure Starship init line is in .bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: 'eval "$(starship init bash)"'
    insertafter: EOF
    state: present
