- name: Include gikeymarcia.neovim role
  include_role:
    name: gikeymarcia.neovim

- name: Clone personal Neovim config
  git:
    repo: "{{ neovim_config_repo }}"
    dest: "{{ neovim_config_path }}"
